version: '3'

services: 
  sonarqube:
    container_name: sonarqube
    image: sonarqube
    ports: 
      - "9000:9000"
    networks:
      - devops
    volumes:
      - "./sonarqubeVol/data:/opt/sonarqube/data"
      - "./sonarqubeVol/extensions:/opt/sonarqube/extensions"
      - "./sonarqubeVol/conf:/opt/sonarqube/conf"
      - "./sonarqubeVol/logs:/opt/sonarqube/logs"

  jenkins: 
    container_name: jenkins
    image: jenkins
    build: jenkins-service/
    ports:
      - "8082:8080"
    networks:
      - devops
    volumes:
      - ./jenkinsVol:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  devops:
