server:
  port: 8091
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: 'jdbc:mysql://mysql:3306/backTest'
    driverClassName: com.mysql.jdbc.Driver
    initialization-mode: always
    data: 'classpath:data.sql'
    platform: mysql
    username: testUser
    password: testPassword
    testWhileIdle: true
    validationQuery: SELECT 1

  session:
    jdbc:
      initialize-schema: always
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: create-drop
      show-sql: false
      use_sql_comments: false
      format_sql: false
    generate-ddl: true
  h2:
    console:
      enabled: false
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry-service:8099/eureka/
  instance:
    prefer-ip-address: true

Feign:
  hystrix:
    enabled: true
  circuitbreaker:
    enabled: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    
hystrix:
  dashboard:
    proxy-stream-allow-list: "*"

management:
  endpoints:
    web:
      exposure:
        include: "*"
      