server:
  port: 8092
  error:
    include-message: always
    include-binding-errors: always

spring:
  data:
    mongodb:
      uri: 'mongodb+srv://miguelangel:12345@cluster0.jxu3e.gcp.mongodb.net/FotosDB'
      database: FotosDB
      option:
        socket-keep-alive: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
Feign:
  hystrix:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      orderService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always