server:
  port: 8092
  error:
    include-message: always
    include-binding-errors: always

spring:
  data:
    mongodb:
      uri: 'mongodb+srv://miguelangel:12345@cluster0.jxu3e.gcp.mongodb.net/FotosDB'
      database: FotosDB
      option:
        socket-keep-alive: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
Feign:
  hystrix:
    enabled: true
    dashboard:
      proxy-stream-allow-list: "*",  "http://localhost:8091/actuator/hystrix.stream", "http://localhost:8091/hystrix.stream"
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, health
      base-path: /
