spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/backTest'
    driverClassName: com.mysql.jdbc.Driver
    initialization-mode: always
    data: 'classpath:data.sql'
    platform: mysql
    username: root
    password: '12345'
    testWhileIdle: true
    validationQuery: SELECT 1
  application:
    name: image-service
    cloud:
      config:
        uri: http://localhost:8080
        username: root
        password: s3cr3t
    boot:
      admin:
        client:
          url: http://localhost:8086
  session:
    jdbc:
      initialize-schema: always
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: create-drop
      show-sql: true
      use_sql_comments: false
      format_sql: false
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  data:
    mongodb:
      uri: 'mongodb+srv://miguelangel:12345@cluster0.jxu3e.gcp.mongodb.net/FotosDB'
      database: FotosDB
      option:
        socket-keep-alive: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
